apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-2.0.0
  labels:
    app: my-app
    version: 2.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
      version: "2.0.0"
  template:
    metadata:
      labels:
        app: my-app
        version: "2.0.0"
    spec:
     containers:
     - name: app-flask
       image: app-flask:2.0.0
       imagePullPolicy: IfNotPresent
       ports:
       - containerPort: 3000
       livenessProbe:
        httpGet:
          path: /health
          port: 3000
        initialDelaySeconds: 10
        timeoutSeconds: 2
        periodSeconds: 5
        failureThreshold: 1
       readinessProbe:
        httpGet:
          path: /health
          port: 3000
        initialDelaySeconds: 2
        periodSeconds: 5
       resources:
         limits:
           memory: "256Mi" #256MB
           cpu: "200m"     #200Mili